import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#6B7280',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 15,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  summaryCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
    marginBottom: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryText: {
    fontSize: 14,
    color: '#6B7280',
    marginLeft: 8,
  },
  summaryPrice: {
    fontSize: 14,
    fontWeight: '600',
    color: '#22C55E',
    marginLeft: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
    marginBottom: 16,
  },
  vehicleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  vehicleCardSelected: {
    borderColor: '#22C55E',
    backgroundColor: '#F0FDF4',
  },
  radioContainer: {
    marginRight: 12,
  },
  radioOuter: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterSelected: {
    borderColor: '#22C55E',
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#22C55E',
  },
  vehicleIcon: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  vehicleIconSelected: {
    backgroundColor: '#F0FDF4',
  },
  vehicleInfo: {
    flex: 1,
  },
  vehicleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  vehiclePlate: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
    marginRight: 8,
  },
  defaultBadge: {
    backgroundColor: '#22C55E',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  defaultText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#fff',
  },
  vehicleModel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#6B7280',
    marginBottom: 2,
  },
  vehicleColor: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  addVehicleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    borderWidth: 2,
    borderColor: '#22C55E',
    borderStyle: 'dashed',
    marginTop: 8,
  },
  addVehicleText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#22C55E',
    marginLeft: 8,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    marginTop: 4,
  },
  footer: {
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  continueButton: {
    backgroundColor: '#22C55E',
    height: 56,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#22C55E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  continueButtonDisabled: {
    backgroundColor: '#D1D5DB',
    shadowOpacity: 0,
    elevation: 0,
  },
  continueText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 0.5,
  },
  modalOverlay: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0, 0, 0, 0.5)',
  justifyContent: 'flex-end',
  zIndex: 1000,
},
modalContent: {
  backgroundColor: '#fff',
  borderTopLeftRadius: 24,
  borderTopRightRadius: 24,
  padding: 20,
  maxHeight: '80%',
},
modalHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: 20,
},
modalTitle: {
  fontSize: 20,
  fontWeight: '700',
  color: '#333',
},
modalLabel: {
  fontSize: 14,
  fontWeight: '600',
  color: '#333',
  marginBottom: 8,
  marginTop: 16,
},
modalInput: {
  backgroundColor: '#F9FAFB',
  borderRadius: 12,
  borderWidth: 1,
  borderColor: '#E5E7EB',
  paddingHorizontal: 16,
  height: 56,
  fontSize: 16,
  color: '#333',
},
typeRow: {
  flexDirection: 'row',
  gap: 12,
},
typeButton: {
  flex: 1,
  alignItems: 'center',
  padding: 16,
  borderRadius: 12,
  backgroundColor: '#F9FAFB',
  borderWidth: 2,
  borderColor: '#E5E7EB',
},
typeButtonActive: {
  backgroundColor: '#22C55E',
  borderColor: '#22C55E',
},
typeButtonText: {
  fontSize: 12,
  fontWeight: '600',
  color: '#6B7280',
  marginTop: 8,
},
typeButtonTextActive: {
  color: '#fff',
},
modalSaveButton: {
  backgroundColor: '#22C55E',
  height: 56,
  borderRadius: 12,
  justifyContent: 'center',
  alignItems: 'center',
  marginTop: 24,
},
modalSaveButtonDisabled: {
  backgroundColor: '#D1D5DB',
},
modalSaveText: {
  fontSize: 16,
  fontWeight: '700',
  color: '#fff',
},
modalCancelButton: {
  height: 56,
  justifyContent: 'center',
  alignItems: 'center',
  marginTop: 12,
},
modalCancelText: {
  fontSize: 16,
  fontWeight: '600',
  color: '#6B7280',
},

manualEntryCard: {
  backgroundColor: '#fff',
  borderRadius: 16,
  padding: 24,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 8,
  elevation: 3,
  alignItems: 'center',
},
manualHeader: {
  width: 80,
  height: 80,
  borderRadius: 40,
  backgroundColor: '#F0FDF4',
  justifyContent: 'center',
  alignItems: 'center',
  marginBottom: 20,
},
manualTitle: {
  fontSize: 20,
  fontWeight: '700',
  color: '#333',
  marginBottom: 8,
  textAlign: 'center',
},
manualSubtitle: {
  fontSize: 14,
  color: '#6B7280',
  marginBottom: 24,
  textAlign: 'center',
},
manualInputGroup: {
  width: '100%',
  marginBottom: 16,
},
manualLabel: {
  fontSize: 14,
  fontWeight: '600',
  color: '#333',
  marginBottom: 8,
},
manualInput: {
  backgroundColor: '#F9FAFB',
  borderRadius: 12,
  borderWidth: 1,
  borderColor: '#E5E7EB',
  paddingHorizontal: 16,
  height: 56,
  fontSize: 16,
  color: '#333',
  width: '100%',
},
manualAddButton: {
  backgroundColor: '#22C55E',
  height: 56,
  borderRadius: 12,
  justifyContent: 'center',
  alignItems: 'center',
  width: '100%',
  marginTop: 8,
  shadowColor: '#22C55E',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.2,
  shadowRadius: 8,
  elevation: 4,
},
manualAddButtonText: {
  fontSize: 16,
  fontWeight: '700',
  color: '#fff',
},
manualNote: {
  fontSize: 12,
  color: '#6B7280',
  marginTop: 16,
  textAlign: 'center',
  fontStyle: 'italic',
},
});